workflows:
  ios-workflow:
    name: iOS Release Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.nadi.fouad
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing
        script: |
          set -e
          set -x
          keychain initialize
      
      - name: Get Flutter packages  
        script: |
          flutter packages pub get
      
      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -execdir pod install \;
      
      - name: Flutter build
        script: |
          flutter build ipa --release \
            --export-options-plist=$HOME/export_options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - your-email@example.com
      app_store_connect:
        auth: integration