workflows:
  ios-workflow:
    name: iOS Release Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.nadi.fouad
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Pod install
        script: |
          cd ios
          pod install
          cd ..
      
      - name: Build IPA
        script: |
          flutter build ipa --release --export-options-plist=$HOME/export_options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - your-email@example.com