workflows:
  ios-workflow:
    name: iOS Release Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.nadi.fouad
      flutter: stable
      xcode: 15.0
      cocoapods: 1.16.2
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      
      - name: Install CocoaPods
        script: |
          sudo gem install cocoapods -v 1.16.2
      
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Clean iOS build
        script: |
          flutter clean
          cd ios
          rm -rf Pods Podfile.lock
          cd ..
      
      - name: Flutter precache and build
        script: |
          flutter precache --ios
          flutter build ios --release --no-codesign
      
      - name: Install pods
        script: |
          cd ios
          pod install --repo-update
          cd ..
      
      - name: Build IPA
        script: |
          flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - your-email@example.com