workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.nadi.fouad
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
      
      - name: Get dependencies
        script: |
          flutter pub get
      
      - name: Generate Flutter config files
        script: |
          cd ios
          flutter precache --ios
          cd ..
          cat > ios/Flutter/Generated.xcconfig << EOF
FLUTTER_ROOT=$HOME/programs/flutter
FLUTTER_APPLICATION_PATH=$PWD
COCOAPODS_PARALLEL_CODE_SIGN=true
FLUTTER_TARGET=lib/main.dart
FLUTTER_BUILD_DIR=build
FLUTTER_BUILD_NAME=1.0.0
FLUTTER_BUILD_NUMBER=1
EXCLUDED_ARCHS[sdk=iphonesimulator*]=i386
EXCLUDED_ARCHS[sdk=iphoneos*]=armv7
DART_OBFUSCATION=false
TRACK_WIDGET_CREATION=true
TREE_SHAKE_ICONS=false
PACKAGE_CONFIG=.dart_tool/package_config.json
EOF
          cat > ios/Flutter/Debug.xcconfig << EOF
#include "Generated.xcconfig"
EOF
          cat > ios/Flutter/Release.xcconfig << EOF
#include "Generated.xcconfig"
EOF
      
      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..
      
      - name: Build ipa
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - your-email@example.com